=== steliosmagalios/university-scheduler/test/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "lectures": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "string",
              "enum": [
                "Aud",
                "Lab"
              ]
            },
            "duration": {
              "type": "integer"
            },
            "professors": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                }
              ]
            },
            "groups": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                }
              ]
            }
          },
          "required": [
            "id",
            "type",
            "duration",
            "professors",
            "groups"
          ]
        }
      ]
    },
    "professors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "availability": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                }
              ]
            }
          },
          "required": [
            "id",
            "availability"
          ]
        }
      ]
    },
    "groups": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "size": {
              "type": "integer"
            },
            "overlapping": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "id",
            "size",
            "overlapping"
          ]
        }
      ]
    },
    "rooms": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "string",
              "enum": [
                "Aud",
                "Lab"
              ]
            },
            "capacity": {
              "type": "integer"
            },
            "availability": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                }
              ]
            }
          },
          "required": [
            "id",
            "type",
            "capacity",
            "availability"
          ]
        }
      ]
    }
  },
  "required": [
    "lectures",
    "professors",
    "groups",
    "rooms"
  ]
}

=== steliosmagalios/university-scheduler/test/tests/4_no_capacity.json
{
  "$schema": "../schema.json",
  "lectures": [
    {
      "id": 1,
      "type": "Aud",
      "duration": 2,
      "professors": [
        1
      ],
      "groups": [
        1
      ]
    }
  ],
  "professors": [
    {
      "id": 1,
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    }
  ],
  "groups": [
    {
      "id": 1,
      "size": 100,
      "overlapping": []
    }
  ],
  "rooms": [
    {
      "id": 1,
      "capacity": 99,
      "type": "Aud",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    }
  ]
}

=== steliosmagalios/university-scheduler/test/tests/7_single_course_more_rooms.json
{
  "$schema": "../schema.json",
  "lectures": [
    {
      "id": 1,
      "type": "Aud",
      "duration": 1,
      "professors": [
        1
      ],
      "groups": [
        1
      ]
    },
    {
      "id": 2,
      "type": "Aud",
      "duration": 1,
      "professors": [
        2
      ],
      "groups": [
        2
      ]
    },
    {
      "id": 3,
      "type": "Aud",
      "duration": 1,
      "professors": [
        1
      ],
      "groups": [
        3
      ]
    },
    {
      "id": 4,
      "type": "Lab",
      "duration": 2,
      "professors": [
        1
      ],
      "groups": [
        4
      ]
    },
    {
      "id": 5,
      "type": "Lab",
      "duration": 2,
      "professors": [
        2
      ],
      "groups": [
        5
      ]
    },
    {
      "id": 6,
      "type": "Lab",
      "duration": 2,
      "professors": [
        3
      ],
      "groups": [
        6
      ]
    },
    {
      "id": 7,
      "type": "Lab",
      "duration": 2,
      "professors": [
        1
      ],
      "groups": [
        7
      ]
    },
    {
      "id": 8,
      "type": "Lab",
      "duration": 2,
      "professors": [
        2
      ],
      "groups": [
        8
      ]
    },
    {
      "id": 9,
      "type": "Lab",
      "duration": 2,
      "professors": [
        3
      ],
      "groups": [
        9
      ]
    }
  ],
  "professors": [
    {
      "id": 1,
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 2,
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 3,
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    }
  ],
  "groups": [
    {
      "id": 1,
      "size": 100,
      "overlapping": [
        1,
        2
      ]
    },
    {
      "id": 2,
      "size": 100,
      "overlapping": [
        3,
        4
      ]
    },
    {
      "id": 3,
      "size": 100,
      "overlapping": [
        5,
        6
      ]
    },
    {
      "id": 4,
      "size": 50,
      "overlapping": [
        1
      ]
    },
    {
      "id": 5,
      "size": 50,
      "overlapping": [
        1
      ]
    },
    {
      "id": 6,
      "size": 50,
      "overlapping": [
        2
      ]
    },
    {
      "id": 7,
      "size": 50,
      "overlapping": [
        2
      ]
    },
    {
      "id": 8,
      "size": 50,
      "overlapping": [
        3
      ]
    },
    {
      "id": 9,
      "size": 50,
      "overlapping": [
        3
      ]
    }
  ],
  "rooms": [
    {
      "id": 1,
      "capacity": 100,
      "type": "Aud",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 2,
      "capacity": 100,
      "type": "Aud",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 3,
      "capacity": 50,
      "type": "Lab",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 4,
      "capacity": 50,
      "type": "Lab",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69
      ]
    },
    {
      "id": 5,
      "capacity": 150,
      "type": "Lab",
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55
      ]
    }
  ]
}

=== steliosmagalios/university-scheduler/test/tests/1_single_lecture.json
{
  "lectures": [
    {
      "id": 1,
      "type": "Aud",
      "duration": 3,
      "professors": [
        1
      ],
      "groups": [
        1
      ]
    }
  ],
  "professors": [
    {
      "id": 1,
      "availability": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    }
  ],
  "groups": [
    {
      "id": 1,
      "size": 10,
      "overlapping": []
    }
  ],
  "rooms": [
    {
      "id": 1,
      "type": "Aud",
      "capacity": 10,
      "availability": [
        1,
        3,
        5,
        6,
        7
      ]
    }
  ]
}
